Remove anyrun, since cfscrape library needs to fixed. With the latest urllib3 version we get: "ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'"